### ISSUE TITLE
The Data.zip format is unknown or the data has been corrupted

### ISSUE THREAD

**Issue by yangwenzhe** [ZzMeei/CS-StarSchemaHIN#1]
The compressed file format is unknown or the data has been corrupted, we do not know what the format of the data looks like.

**Comment by yangqin-jiang** [comment]
Hi, we have updated the README and provide other methods for dataset downloading, please refer to it. 

If you have any further questions, please let me know.

**Comment by yangwenzhe** [comment]
Thank you for your response. The issue has been resolved.
